//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKullaniciKaydi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int Id { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Kullanici_Parolasi { get; set; }
        public string Kullanici_Emaili { get; set; }
        public System.DateTime Tarih { get; set; }
    }
}
